name: Policy-Check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  secret-scan:
    name: GitLeaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # biar scan semua history commit agak dongo sih kalau commit ada 10rb gimana wkwkw

      - name: Secret Scan (GitLeaks)
        uses: gitleaks/gitleaks-action@v2
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  policy-checker:
    name: Conftest Policy Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Conftest Policy
        run: |
          docker run --rm -v "$GITHUB_WORKSPACE:/project" openpolicyagent/conftest:v0.68.2 \
            test multienv-app/modules/app-stack/main.tf -p multienv-app/policy
