name: Policy-Check

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  policy-checker:
    name: Conftest Policy Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install conftest
        run: |
          CONFTEST_VERSION=0.68.2
          curl -sSL "https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz" -o /tmp/conftest.tar.gz
          tar -xzf /tmp/conftest.tar.gz -C /tmp conftest
          sudo mv /tmp/conftest /usr/local/bin/
          conftest --version

      - name: Run Conftest Policy
        run: conftest test multienv-app/modules/app-stack/main.tf -p multienv-app/policy

  